In [ ]:
import git
repository_url = "https://github.com/PhonePe/pulse.git"
#estination_directory = "C:/Users/INFO/Desktop/PHONE_PAY/data"
destination_directory = "C:\Users\Dell\OneDrive\Desktop\projects\phonepay_project"
git.Repo.clone_from(repository_url, destination_directory)

In [12]:
#Aggregated Transaction
import pandas as pd
import json
import os

#This is to direct the path to get the data as states

path=r"C:\Users\Dell\OneDrive\Desktop\projects\phonepay_project\data\aggregated\transaction\country\india\state"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transacion_type':[], 'Transacion_count':[], 'Transacion_amount':[]}

for i in Agg_state_list:
    p_i=path+"\\"+i
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+"\\"+j
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+"\\"+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
                Name=z['name']
                count=z['paymentInstruments'][0]['count']
                amount=z['paymentInstruments'][0]['amount']
                clm['Transacion_type'].append(Name)
                clm['Transacion_count'].append(count)
                clm['Transacion_amount'].append(amount)
                clm['State'].append(i)
                clm['Year'].append(j)
                clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
Agg_Trans=pd.DataFrame(clm)

In [14]:
# Replacing data as per geo 
Agg_Trans["State"]=Agg_Trans["State"].str.title()
Agg_Trans["State"]=Agg_Trans["State"].str.replace("-"," ")
Agg_Trans["State"]=Agg_Trans["State"].str.replace("Andaman & Nicobar Islands","Andaman & Nicobar")
Agg_Trans["State"]=Agg_Trans["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu","Dadra and Nagar Haveli and Daman and Diu")
# Agg_Trans["State"].unique()

In [16]:
#Aggregated Uesr
import pandas as pd
import json
import os

#This is to direct the path to get the data as states

path=r"C:\Users\Dell\OneDrive\Desktop\projects\phonepay_project\data\aggregated\user\country\india\state"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'User_brand':[], 'User_count':[], 'User_percentage':[]}

for i in Agg_state_list:
        p_i=path+"\\"+i
        Agg_yr=os.listdir(p_i)
        for j in Agg_yr:
                p_j=p_i+"\\"+j
                Agg_yr_list=os.listdir(p_j)
                for k in Agg_yr_list:
                        p_k=p_j+"\\"+k
                        Data=open(p_k,'r')
                        D=json.load(Data)
                        try:
                                for z in D['data']['usersByDevice']:
                                        brand=z['brand']
                                        count=z['count']
                                        percentage=z['percentage']
                                        clm['User_brand'].append(brand)
                                        clm['User_count'].append(count)
                                        clm['User_percentage'].append(percentage)
                                        clm['State'].append(i)
                                        clm['Year'].append(j)
                                        clm['Quater'].append(int(k.strip('.json')))
                        except:
                                pass
# #Succesfully created a dataframe
Agg_user=pd.DataFrame(clm)

In [17]:
# Replacing data as per geo 
Agg_user["State"]=Agg_user["State"].str.title()
Agg_user["State"]=Agg_user["State"].str.replace("-"," ")
Agg_user["State"]=Agg_user["State"].str.replace("Andaman & Nicobar Islands","Andaman & Nicobar")
Agg_user["State"]=Agg_user["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu","Dadra and Nagar Haveli and Daman and Diu")

In [25]:
#Map Transaction
import pandas as pd
import json
import os

#This is to direct the path to get the data as states

path=r"C:\Users\Dell\OneDrive\Desktop\projects\phonepay_project\data\map\transaction\hover\country\india\state"
map_state_list=os.listdir(path)
map_state_list
# map_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transacion_region':[], 'Transacion_count':[], 'Transacion_amount':[]}

for i in map_state_list:
    p_i=path+"\\"+i
    map_yr=os.listdir(p_i)
    for j in map_yr:
        p_j=p_i+"\\"+j
        map_yr_list=os.listdir(p_j)
        for k in map_yr_list:
            p_k=p_j+"\\"+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['hoverDataList']:
                Name=z['name']
                count=z["metric"][0]['count']
                amount=z["metric"][0]['amount']
                clm['Transacion_region'].append(Name)
                clm['Transacion_count'].append(count)
                clm['Transacion_amount'].append(amount)
                clm['State'].append(i)
                clm['Year'].append(j)
                clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
map_Trans=pd.DataFrame(clm)

In [26]:
# Replacing data as per geo 
map_Trans["State"]=map_Trans["State"].str.title()
map_Trans["State"]=map_Trans["State"].str.replace("-"," ")
map_Trans["State"]=map_Trans["State"].str.replace("Andaman & Nicobar Islands","Andaman & Nicobar")
map_Trans["State"]=map_Trans["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu","Dadra and Nagar Haveli and Daman and Diu")

In [28]:
#Map Uesr
import pandas as pd
import json
import os

#This is to direct the path to get the data as states

path=r"C:\Users\Dell\OneDrive\Desktop\projects\phonepay_project\data\map\user\hover\country\india\state"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'User_region':[], 'User_count':[]}

for i in Agg_state_list:
        p_i=path+"\\"+i
        Agg_yr=os.listdir(p_i)
        for j in Agg_yr:
                p_j=p_i+"\\"+j
                Agg_yr_list=os.listdir(p_j)
                for k in Agg_yr_list:
                        p_k=p_j+"\\"+k
                        Data=open(p_k,'r')
                        D=json.load(Data)
                        for z,y in D['data']['hoverData'].items():
                                region=z
                                count=y['registeredUsers']
                                clm['User_region'].append(region)
                                clm['User_count'].append(count)
                                clm['State'].append(i)
                                clm['Year'].append(j)
                                clm['Quater'].append(int(k.strip('.json')))
# #Succesfully created a dataframe
map_user=pd.DataFrame(clm)

In [29]:
# Replacing data as per geo 
map_user["State"]=map_user["State"].str.title()
map_user["State"]=map_user["State"].str.replace("-"," ")
map_user["State"]=map_user["State"].str.replace("Andaman & Nicobar Islands","Andaman & Nicobar")
map_user["State"]=map_user["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu","Dadra and Nagar Haveli and Daman and Diu")

In [31]:
#Top Transaction
import pandas as pd
import json
import os

#This is to direct the path to get the data as states

path=r"C:\Users\Dell\OneDrive\Desktop\projects\phonepay_project\data\top\transaction\country\india\state"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transacion_type':[], 'Transacion_count':[], 'Transacion_amount':[]}

for i in Agg_state_list:
    p_i=path+"\\"+i
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+"\\"+j
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+"\\"+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['districts']:
                Name=z['entityName']
                count=z["metric"]['count']
                amount=z['metric']['amount']
                clm['Transacion_type'].append(Name)
                clm['Transacion_count'].append(count)
                clm['Transacion_amount'].append(amount)
                clm['State'].append(i)
                clm['Year'].append(j)
                clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
Top_Trans=pd.DataFrame(clm)

In [32]:
# Replacing data as per geo 
Top_Trans["State"]=Top_Trans["State"].str.title()
Top_Trans["State"]=Top_Trans["State"].str.replace("-"," ")
Top_Trans["State"]=Top_Trans["State"].str.replace("Andaman & Nicobar Islands","Andaman & Nicobar")
Top_Trans["State"]=Top_Trans["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu","Dadra and Nagar Haveli and Daman and Diu")

In [34]:
#Top Uesr
import pandas as pd
import json
import os

#This is to direct the path to get the data as states

path=r"C:\Users\Dell\OneDrive\Desktop\projects\phonepay_project\data\top\user\country\india\state"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'User_region':[], 'User_count':[]}

for i in Agg_state_list:
        p_i=path+"\\"+i
        Agg_yr=os.listdir(p_i)
        for j in Agg_yr:
                p_j=p_i+"\\"+j
                Agg_yr_list=os.listdir(p_j)
                for k in Agg_yr_list:
                        p_k=p_j+"\\"+k
                        Data=open(p_k,'r')
                        D=json.load(Data)
                        for z in D['data']["districts"]:
                                name=z["name"]
                                count=z["registeredUsers"]
                                clm['User_region'].append(name)
                                clm['User_count'].append(count)
                                clm['State'].append(i)
                                clm['Year'].append(j)
                                clm['Quater'].append(int(k.strip('.json')))
# #Succesfully created a dataframe
Top_user=pd.DataFrame(clm)

In [35]:
# Replacing data as per geo 
Top_user["State"]=Top_user["State"].str.title()
Top_user["State"]=Top_user["State"].str.replace("-"," ")
Top_user["State"]=Top_user["State"].str.replace("Andaman & Nicobar Islands","Andaman & Nicobar")
Top_user["State"]=Top_user["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu","Dadra and Nagar Haveli and Daman and Diu")

In [50]:
#Storing dataframes in sql
#mysql server connection
import mysql.connector
mydb = mysql.connector.connect(host="localhost",user="root",password="")
mycursor = mydb.cursor(buffered=True)

In [57]:
#table creation
mycursor.execute("use phonepe")
mycursor.execute("create table Agg_Trans(State varchar(40),Year int,Quater int,Transacion_type varchar(100),Transacion_count bigint,Transacion_amount bigint)")
mycursor.execute("create table Agg_user(State varchar(40),Year int,Quater int,User_brand varchar(100),User_count bigint,User_percentage float)")
mycursor.execute("create table map_Trans(State varchar(40),Year int,Quater int,Transacion_region varchar(100),Transacion_count bigint,Transacion_amount bigint)")
mycursor.execute("create table map_user(State varchar(40),Year int,Quater int,User_region varchar(100),User_count bigint)")
mycursor.execute("create table Top_Trans(State varchar(40),Year int,Quater int,Transacion_type varchar(100),Transacion_count bigint,Transacion_amount bigint)")
mycursor.execute("create table Top_user(State varchar(40),Year int,Quater int,User_region varchar(100),User_count bigint)")
mydb.commit()

In [58]:
#inserting values to Agg_Tran
data=Agg_Trans.values.tolist()
quary = "INSERT INTO Agg_Trans(State,Year,Quater,Transacion_type,Transacion_count,Transacion_amount) VALUES(%s,%s,%s,%s,%s,%s)"
# Execute the SQL query for each row of the DataFrame
mycursor.executemany(quary, data)
mydb.commit()

In [59]:
#inserting values to Agg_user
data=Agg_user.values.tolist()
quary = "INSERT INTO Agg_user(State,Year,Quater,User_brand,User_count,User_percentage) VALUES(%s,%s,%s,%s,%s,%s)"
# Execute the SQL query for each row of the DataFrame
mycursor.executemany(quary, data)
mydb.commit()

In [60]:
#inserting values to map_Trans
data=map_Trans.values.tolist()
for i in data:
    quary = "INSERT INTO phonepe.map_Trans(State,Year,Quater,Transacion_region,Transacion_count,Transacion_amount) VALUES(%s,%s,%s,%s,%s,%s)"
    # Execute the SQL query for each row of the DataFrame
    mycursor.execute(quary,i)
mydb.commit()

In [61]:
#inserting values to map_user
data=map_user.values.tolist()
for i in data:
    quary = "INSERT INTO phonepe.map_user(State,Year,Quater,User_region,User_count) VALUES(%s,%s,%s,%s,%s)"
    # Execute the SQL query for each row of the DataFrame
    mycursor.execute(quary,i)
mydb.commit()

In [62]:
#inserting values to Top_Trans
data=Top_Trans.values.tolist()
for i in data:
    quary = "INSERT INTO phonepe.Top_Trans(State,Year,Quater,Transacion_type,Transacion_count,Transacion_amount) VALUES(%s,%s,%s,%s,%s,%s)"
    # Execute the SQL query for each row of the DataFrame
    mycursor.execute(quary,i)
mydb.commit()

In [63]:
#inserting values to Top_user
data=Top_user.values.tolist()
for i in data:
    quary = "INSERT INTO phonepe.Top_user(State,Year,Quater,User_region,User_count) VALUES(%s,%s,%s,%s,%s)"
    # Execute the SQL query for each row of the DataFrame
    mycursor.execute(quary,i)
mydb.commit()